/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sofosim.nadico;

import org.frogberry.propertiesWriter.PropertiesWriter;
import org.frogberry.propertiesWriter.annotations.ManagedProperty;


/**
 *
 * @author cfrantz
 */
public class NAdicoUiController extends javax.swing.JFrame {

    /**
     * Creates new form NAdicoUiController
     */
    public NAdicoUiController() {
        initComponents();
        btnIndividualTags.setSelected(CommunicationSpace.showTagsOnIndividualUi);
        btnSuggestedRules.setSelected(CommunicationSpace.showSuggestedRulesOnIndividualUi);
        btnCodifiedRules.setSelected(CommunicationSpace.showCodifiedRulesOnIndividualUi);
        PropertiesWriter.assignProperties(this);
        btnIndividualTagsActionPerformed(null);
        btnSuggestedRulesActionPerformed(null);
        btnCodifiedRulesActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIndividualTags = new javax.swing.JToggleButton();
        btnSuggestedRules = new javax.swing.JToggleButton();
        btnCodifiedRules = new javax.swing.JToggleButton();
        btnShowName = new javax.swing.JToggleButton();

        setTitle("nADICO Ui Output Controller");

        btnIndividualTags.setText("Show Individual Tags");
        btnIndividualTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndividualTagsActionPerformed(evt);
            }
        });

        btnSuggestedRules.setText("Show Individuals' suggested Rules");
        btnSuggestedRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuggestedRulesActionPerformed(evt);
            }
        });

        btnCodifiedRules.setText("Show established codified Rules");
        btnCodifiedRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodifiedRulesActionPerformed(evt);
            }
        });

        btnShowName.setText("Show Name");
        btnShowName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowName)
                    .addComponent(btnCodifiedRules)
                    .addComponent(btnSuggestedRules)
                    .addComponent(btnIndividualTags))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIndividualTags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuggestedRules)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCodifiedRules)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndividualTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndividualTagsActionPerformed
        if(btnIndividualTags.isSelected()){
            CommunicationSpace.showTagsOnIndividualUi = true;
        } else {
            CommunicationSpace.showTagsOnIndividualUi = false;
        }
        PropertiesWriter.saveProperties(this);
    }//GEN-LAST:event_btnIndividualTagsActionPerformed

    private void btnSuggestedRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuggestedRulesActionPerformed
        if(btnSuggestedRules.isSelected()){
            CommunicationSpace.showSuggestedRulesOnIndividualUi = true;
        } else {
            CommunicationSpace.showSuggestedRulesOnIndividualUi = false;
        }
        PropertiesWriter.saveProperties(this);
    }//GEN-LAST:event_btnSuggestedRulesActionPerformed

    private void btnCodifiedRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodifiedRulesActionPerformed
        if(btnCodifiedRules.isSelected()){
            CommunicationSpace.showCodifiedRulesOnIndividualUi = true;
        } else {
            CommunicationSpace.showCodifiedRulesOnIndividualUi = false;
        }
        PropertiesWriter.saveProperties(this);
    }//GEN-LAST:event_btnCodifiedRulesActionPerformed

    private void btnShowNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowNameActionPerformed
        if(btnShowName.isSelected()){
            CommunicationSpace.showAgentNameOnIndividualUi = true;
        } else {
            CommunicationSpace.showAgentNameOnIndividualUi = false;
        }
        PropertiesWriter.saveProperties(this);
    }//GEN-LAST:event_btnShowNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NAdicoUiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NAdicoUiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NAdicoUiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NAdicoUiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NAdicoUiController().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    @ManagedProperty
    private javax.swing.JToggleButton btnCodifiedRules;
    @ManagedProperty
    private javax.swing.JToggleButton btnIndividualTags;
    @ManagedProperty
    private javax.swing.JToggleButton btnShowName;
    @ManagedProperty
    private javax.swing.JToggleButton btnSuggestedRules;
    // End of variables declaration//GEN-END:variables
}
